# Generated by Django 3.2.5 on 2022-01-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('file', models.FileField(blank=True, upload_to='problem_statements/dataset/')),
                ('link', models.URLField(blank=True, max_length=100)),
                ('domain_bucket', models.CharField(choices=[('Agriculture and Rural Development', 'Agriculture and Rural Development'), ('Clean Water', 'Clean Water'), ('Robotics & Drones', 'Robotics & Drones'), ('Healthcare & Biomedical Devices', 'Healthcare & Biomedical Devices'), ('Energy / Renewable Energy', 'Energy / Renewable Energy'), ('Security & Surveillance', 'Security & Surveillance'), ('Smart Communication', 'Smart Communication'), ('Smart Vehicles', 'Smart Vehicles'), ('Software - Mobile App development', 'Software - Mobile App development'), ('Miscellaneous', 'Miscellaneous'), ('Software - Web App development', 'Software - Web App development'), ('Travel and Tourism', 'Travel and Tourism'), ('Finance', 'Finance'), ('Life Sciences', 'Life Sciences'), ('Waste Management', 'Waste Management'), ('Food Technology', 'Food Technology'), ('Smart Education', 'Smart Education'), ('Smart Cities', 'Smart Cities'), ('Sports and Fitness', 'Sports and Fitness'), ('Smart Textiles', 'Smart Textiles'), ('Sustainable Environment', 'Sustainable Environment')], max_length=50)),
                ('prize', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
    ]
