# Generated by Django 3.2.5 on 2022-01-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_coursematerial_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='prize',
            field=models.CharField(max_length=100),
        ),
    ]
