# Generated by Django 3.2.5 on 2022-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_coursematerial_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('country', models.CharField(default='India', max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('idproof', models.FileField(upload_to='teacher/id_proof')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_mobile_verified', models.BooleanField(default=False)),
                ('first_login', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
